<script lang="ts">
  import type { AgentRecord } from "$lib/types";
  import { transcripts, type Turn } from "$lib/state/index.svelte";
  import { cn } from "$lib/utils";

  let { agents }: { agents: AgentRecord[] } = $props();

  /// Build an attribution map agentId → AgentRecord for O(1) lookup when
  /// rendering each turn. The unified view merges across all the project's
  /// agents — without per-turn attribution the reader can't tell who said
  /// what.
  const agentById = $derived.by(() => {
    const map: Record<string, AgentRecord> = {};
    for (const a of agents) map[a.id] = a;
    return map;
  });

  /// Flatten + chronologically sort. ISO-8601 strings sort lexicographically
  /// for the primary key. Same-timestamp ties resolve via JavaScript's
  /// stable Array.sort (ES2019+): turns retain their insertion order from
  /// the `transcripts[agent.id]` arrays (which the reducer appends in
  /// event-arrival order — chronologically correct for the same agent),
  /// with cross-agent ties falling back to the agents-array iteration
  /// order below (project-registration order).
  ///
  /// **Why no turn_id tie-breaker.** User-turn ids are generated by
  /// `crypto.randomUUID()` (v4-random), so lexicographic comparison
  /// against the dispatcher's v7-time-ordered agent turn_ids is
  /// effectively random. Stable sort + insertion order is the
  /// deterministic tie-break.
  ///
  /// **If disk-loaded transcripts surface real cross-agent
  /// same-millisecond timestamp collisions**, promote to an explicit
  /// per-turn `sort_index` populated by the reducer / hydrator. Not
  /// observed yet.
  const allTurns = $derived.by(() => {
    const out: Turn[] = [];
    for (const agent of agents) {
      const slice = transcripts[agent.id] ?? [];
      for (const turn of slice) out.push(turn);
    }
    out.sort((a, b) => a.started_at.localeCompare(b.started_at));
    return out;
  });

  function agentName(agentId: string): string {
    return agentById[agentId]?.name ?? "unknown";
  }

  function harnessBadgeClass(agentId: string): string {
    const harness = agentById[agentId]?.harness;
    if (harness === "claude_code") return "bg-orange-100 text-orange-800";
    if (harness === "codex") return "bg-blue-100 text-blue-800";
    return "bg-neutral-100 text-neutral-800";
  }

  function harnessLabel(agentId: string): string {
    const harness = agentById[agentId]?.harness;
    if (harness === "claude_code") return "Claude";
    if (harness === "codex") return "Codex";
    return "?";
  }

  // Auto-pin to bottom unless the user has scrolled up. Mirrors the
  // legacy Transcript.svelte behavior — keeps the reader at the live edge
  // during streaming, but doesn't yank them away if they scroll back to
  // read earlier turns.
  let container = $state<HTMLDivElement | null>(null);
  let pinned = $state<boolean>(true);

  function onScroll(): void {
    if (!container) return;
    const distanceFromBottom =
      container.scrollHeight - container.scrollTop - container.clientHeight;
    pinned = distanceFromBottom < 32;
  }

  /// Fine-grained scroll signal. Length-based dependencies alone miss
  /// **two** in-place mutation patterns the reducers produce:
  ///
  /// 1. Text-chunk coalescing — adjacent content_chunks update the
  ///    existing `TextChunk.text` field; `items.length` stays constant.
  ///    This is the common Claude-streaming path (every chunk after
  ///    the first).
  /// 2. Tool completion — `tool_completed` fills `output` / `is_error` /
  ///    `completed_at` on an existing tool item; `items.length` stays
  ///    constant. Common for a turn that ends with tool output (no
  ///    closing text from the model).
  ///
  /// Both are fixed by reading the mutated fields (`text`, `output`,
  /// `completed_at`) into the signal — Svelte 5 reactivity tracks the
  /// reads and re-runs the derived when those fields change. The signal
  /// grows monotonically with total content (millions of chars for
  /// pathological transcripts, well within Number precision).
  ///
  /// O(turns × items) per state change — fine because $derived caches
  /// and re-runs only when one of the tracked reads actually changes.
  /// If long hydrated transcripts surface this as a perf hotspot, the
  /// fix is to cache a counter on `AgentRuntime` and increment in the
  /// reducer instead of scanning.
  const scrollSignal = $derived.by(() => {
    let n = allTurns.length;
    for (const turn of allTurns) {
      if (turn.role === "user") {
        n += turn.text.length;
        continue;
      }
      n += turn.items.length;
      for (const item of turn.items) {
        if (item.item_kind === "text") {
          n += item.text.length;
        } else {
          if (item.completed_at !== undefined) n += 1;
          n += item.output?.length ?? 0;
        }
      }
    }
    return n;
  });

  $effect(() => {
    void scrollSignal;
    if (pinned && container) {
      container.scrollTop = container.scrollHeight;
    }
  });
</script>

<div
  bind:this={container}
  onscroll={onScroll}
  data-testid="unified-transcript"
  class="flex-1 overflow-y-auto p-4"
>
  {#if allTurns.length === 0}
    <p class="text-sm text-neutral-500">No messages yet. Type a prompt below.</p>
  {/if}
  <div class="space-y-4">
    {#each allTurns as turn (turn.turn_id)}
      <div class="space-y-1" data-testid="turn" data-role={turn.role}>
        <div class="flex items-center gap-2 text-xs font-semibold tracking-wide uppercase">
          {#if turn.role === "user"}
            <span class="text-neutral-500">You</span>
            <span class="text-neutral-400">→</span>
            <span class="font-mono text-neutral-700" data-testid="turn-recipient">
              {agentName(turn.agent_id)}
            </span>
          {:else}
            <span class="font-mono text-neutral-700" data-testid="turn-agent-name">
              {agentName(turn.agent_id)}
            </span>
            <span class={cn("rounded px-1.5 py-0.5 text-[10px]", harnessBadgeClass(turn.agent_id))}>
              {harnessLabel(turn.agent_id)}
            </span>
            {#if turn.status === "streaming"}
              <span class="text-amber-700" data-testid="turn-streaming">streaming…</span>
            {:else if turn.status === "failed"}
              <span class="text-red-700">failed</span>
            {/if}
          {/if}
        </div>
        {#if turn.role === "user"}
          <div class="text-sm whitespace-pre-wrap text-neutral-900">{turn.text}</div>
        {:else}
          <!--
            Render items in order. Codex emits one whole agent_message item
            per turn — until that lands, `items` is empty for the duration
            of the streaming state. Show a "processing…" indicator so the
            UI doesn't look frozen.
          -->
          {#if turn.status === "streaming" && turn.items.length === 0}
            <div class="text-xs text-neutral-500 italic" data-testid="turn-processing">
              processing…
            </div>
          {/if}
          <!--
            Index-keyed render relies on the reducer's append-only /
            mutate-in-place invariant for `items` (tool_completed
            updates the existing item at its original index; never
            reorders, never inserts). If items ever gain insertion or
            reordering semantics, switch to keying by a stable id like
            item.tool_use_id (with a synthesized key for text chunks).
          -->
          {#each turn.items as item, i (i)}
            {#if item.item_kind === "text"}
              <div class="text-sm whitespace-pre-wrap text-neutral-800">{item.text}</div>
            {:else}
              <div
                class="rounded border border-neutral-200 bg-neutral-50 p-2 text-xs"
                data-testid="turn-tool"
                data-tool-use-id={item.tool_use_id}
              >
                <div class="flex items-center gap-1.5 font-semibold text-neutral-700">
                  <span
                    class={cn(
                      "rounded px-1 py-0.5 text-[9px] uppercase",
                      item.kind === "mcp"
                        ? "bg-blue-100 text-blue-800"
                        : "bg-neutral-200 text-neutral-700",
                    )}
                  >
                    {item.kind}
                  </span>
                  <span class="font-mono">{item.name}</span>
                  {#if item.completed_at === undefined}
                    <span class="ml-auto text-amber-700 italic">running…</span>
                  {:else if item.is_error}
                    <span class="ml-auto text-red-700">error</span>
                  {/if}
                </div>
                {#if item.output !== undefined}
                  <pre
                    class={cn(
                      "mt-1 max-h-40 overflow-y-auto font-mono text-[11px] whitespace-pre-wrap",
                      item.is_error ? "text-red-800" : "text-neutral-600",
                    )}>{item.output}</pre>
                {/if}
              </div>
            {/if}
          {/each}
          {#if turn.status === "failed" && turn.error}
            <div class="text-xs text-red-700" data-testid="turn-error">{turn.error}</div>
          {/if}
        {/if}
      </div>
    {/each}
  </div>
</div>
